[server]
port = 8501
address = "localhost"
maxUploadSize = 5

[browser]
serverAddress = "localhost"
serverPort = 8501

[theme]
base="dark"
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
